#!/usr/bin/env bash
# gen-docs.sh — Doc compiler for home-setup governance framework
# Reads audit-spec.json + skills-catalog.json, generates:
#   - docs/generated/traceability.md (principle->goal->check map + Mermaid)
#   - docs/generated/skills-reference.md (catalog-derived skill table)
# Also validates markdown links in docs.
# Usage: bash scripts/gen-docs.sh [--check]

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHECK_MODE=false
[ "${1:-}" = "--check" ] && CHECK_MODE=true

# macOS realpath fallback
_realpath() {
  local dir base
  dir="$(cd "$(dirname "$1")" 2>/dev/null && pwd)" || return 1
  base="$(basename "$1")"
  echo "$dir/$base"
}

# --- Prerequisites ---
if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq is required. Install via: brew install jq" >&2
  exit 1
fi

SPEC="$REPO_ROOT/audit-spec.json"
CATALOG="$REPO_ROOT/skills-catalog.json"

for f in "$SPEC" "$CATALOG"; do
  if [ ! -f "$f" ]; then
    echo "ERROR: $(basename "$f") not found at $REPO_ROOT" >&2
    exit 1
  fi
  if ! jq empty "$f" 2>/dev/null; then
    echo "ERROR: $(basename "$f") is not valid JSON" >&2
    exit 1
  fi
done

TMPDIR=$(mktemp -d)
cleanup() { rm -rf "$TMPDIR"; }
trap cleanup EXIT

# --- Generate traceability.md ---
TRACE_FILE="$TMPDIR/traceability.md"
{
  echo "# Traceability Map"
  echo ""
  echo "AUTO-GENERATED by \`bash scripts/gen-docs.sh\`. Do not edit manually."
  echo ""
  echo "Principle -> Goal -> Check mappings derived from \`audit-spec.json\`."
  echo ""
  echo "## Coverage Table"
  echo ""
  echo "| Goal | Type | Informed by | Checks |"
  echo "|------|------|-------------|--------|"

  jq -r '.goals[] | "\(.id)|\(.type)|\(.informed_by | join(", "))|\(.id)"' "$SPEC" | while IFS='|' read -r gid gtype ginformed _; do
    checks=$(jq -r --arg gid "$gid" '[.checks[] | select(.goals[] == $gid) | .id] | join(", ")' "$SPEC")
    [ -z "$checks" ] && checks="(none)"
    echo "| $gid | $gtype | $ginformed | $checks |"
  done

  echo ""
  echo "## Mermaid Diagram"
  echo ""
  echo '```mermaid'
  echo "graph LR"

  # Principle nodes
  jq -r '.goals[].informed_by[]' "$SPEC" | sort -u | while read -r p; do
    echo "  ${p}[${p}]"
  done

  # Goal nodes
  jq -r '.goals[] | "  \(.id)[\(.id): \(.name)]"' "$SPEC"

  # Check nodes
  jq -r '.checks[] | "  C_\(.id | gsub("[.]"; "_"))[\(.id): \(.title)]"' "$SPEC"

  # Principle -> Goal edges
  jq -r '.goals[] | . as $g | .informed_by[] | "\(.) --> \($g.id)"' "$SPEC" | sort -u

  # Goal -> Check edges
  jq -r '.checks[] | . as $c | .goals[] | "\(.) --> C_\($c.id | gsub("[.]"; "_"))"' "$SPEC"

  echo '```'
} > "$TRACE_FILE"

# --- Generate skills-reference.md ---
SKILLS_FILE="$TMPDIR/skills-reference.md"
{
  echo "# Skills Reference"
  echo ""
  echo "AUTO-GENERATED by \`bash scripts/gen-docs.sh\`. Do not edit manually."
  echo ""
  echo "Derived from \`skills-catalog.json\`."
  echo ""

  UPSTREAM_COUNT=$(jq '[.skills[] | select(.source == "gstack")] | length' "$CATALOG")
  CUSTOM_COUNT=$(jq '[.skills[] | select(.source == "custom") | select(.status != "removed")] | length' "$CATALOG")
  echo "**Total:** $((UPSTREAM_COUNT + CUSTOM_COUNT)) skills ($UPSTREAM_COUNT upstream, $CUSTOM_COUNT custom)"
  echo ""

  echo "## Upstream Skills (gstack)"
  echo ""
  echo "| Skill | Description | Dependencies |"
  echo "|-------|-------------|--------------|"
  jq -r '.skills[] | select(.source == "gstack") | "| /\(.name) | \(.description) | \(.dependencies | join(", ") // "none") |"' "$CATALOG"

  echo ""
  echo "## Custom Skills"
  echo ""
  echo "| Skill | Description | Dependencies |"
  echo "|-------|-------------|--------------|"
  jq -r '.skills[] | select(.source == "custom") | select(.status != "removed") | "| /\(.name) | \(.description) | \(.dependencies | join(", ") // "none") |"' "$CATALOG"
} > "$SKILLS_FILE"

# --- Validate markdown links ---
echo "=== gen-docs.sh ==="
LINK_ERRORS=0

validate_links() {
  local file="$1"
  local dir
  dir="$(dirname "$file")"
  # Extract markdown links [text](path) excluding http/https and anchors
  { grep -oE '\[([^]]*)\]\(([^)]*)\)' "$file" 2>/dev/null || true; } | while read -r match; do
    path=$(echo "$match" | sed 's/.*(\(.*\))/\1/')
    # Skip external URLs
    case "$path" in
      http://*|https://*|mailto:*) continue ;;
      \#*) continue ;;  # anchor-only
    esac
    # Strip anchor from path
    path="${path%%#*}"
    [ -z "$path" ] && continue
    # Resolve relative to the file's directory
    resolved="$(_realpath "$dir/$path" 2>/dev/null)" || resolved=""
    if [ -z "$resolved" ] || [ ! -e "$resolved" ]; then
      echo "  BROKEN LINK in $(basename "$file"): $path" >&2
      LINK_ERRORS=$((LINK_ERRORS + 1))
    fi
  done
}

for doc in "$REPO_ROOT"/docs/generated/*.md "$REPO_ROOT"/docs/*/PRD.md "$REPO_ROOT/README.md" "$REPO_ROOT/CLAUDE.md"; do
  [ -f "$doc" ] || continue
  validate_links "$doc"
done

# --- Check mode or write ---
if $CHECK_MODE; then
  STALE=0
  for pair in "docs/generated/traceability.md:$TRACE_FILE" "docs/generated/skills-reference.md:$SKILLS_FILE"; do
    target="${pair%%:*}"
    generated="${pair##*:}"
    if [ ! -f "$REPO_ROOT/$target" ]; then
      echo "STALE: $target does not exist"
      STALE=$((STALE + 1))
    elif ! diff -q "$REPO_ROOT/$target" "$generated" >/dev/null 2>&1; then
      echo "STALE: $target is out of date"
      STALE=$((STALE + 1))
    fi
  done
  if [ $STALE -gt 0 ]; then
    echo "FAILED: $STALE file(s) need regeneration. Run: bash scripts/gen-docs.sh" >&2
    exit 1
  fi
  echo "PASSED: all generated docs are up to date."
  exit 0
fi

# --- Write output ---
mkdir -p "$REPO_ROOT/docs/generated"
cp "$TRACE_FILE" "$REPO_ROOT/docs/generated/traceability.md"
cp "$SKILLS_FILE" "$REPO_ROOT/docs/generated/skills-reference.md"
echo "Generated: docs/generated/traceability.md"
echo "Generated: docs/generated/skills-reference.md"
echo "Link errors: $LINK_ERRORS"
echo "=== gen-docs.sh complete ==="
